/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitiesResponsePositions } from './entitiesResponsePositions';

export class EntitiesResponseEntities {
    /**
    * Entity type
    */
    'type'?: string;
    /**
    * Entity attributes. Depends on entity type
    */
    'attributes'?: { [key: string]: any; };
    /**
    * Entity positions in text
    */
    'positions'?: Array<EntitiesResponsePositions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "positions",
            "baseName": "positions",
            "type": "Array<EntitiesResponsePositions>"
        }    ];

    static getAttributeTypeMap() {
        return EntitiesResponseEntities.attributeTypeMap;
    }
}

