/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FactsResponsePositions } from './factsResponsePositions';

export class FactsResponseFacts {
    /**
    * Fact type
    */
    'type'?: string;
    /**
    * Fact attributes. Depends on fact type
    */
    'attributes'?: { [key: string]: any; };
    /**
    * Fact positions in text
    */
    'positions'?: Array<FactsResponsePositions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "positions",
            "baseName": "positions",
            "type": "Array<FactsResponsePositions>"
        }    ];

    static getAttributeTypeMap() {
        return FactsResponseFacts.attributeTypeMap;
    }
}

