/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FactsResponseDocuments } from './factsResponseDocuments';

export class FactsResponse {
    'documents'?: Array<FactsResponseDocuments>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<FactsResponseDocuments>"
        }    ];

    static getAttributeTypeMap() {
        return FactsResponse.attributeTypeMap;
    }
}

