/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FactsResponseFacts } from './factsResponseFacts';

export class FactsResponseDocuments {
    /**
    * Index of document in input documents array
    */
    'id'?: number;
    /**
    * Result of facts operation
    */
    'facts'?: Array<FactsResponseFacts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "facts",
            "baseName": "facts",
            "type": "Array<FactsResponseFacts>"
        }    ];

    static getAttributeTypeMap() {
        return FactsResponseDocuments.attributeTypeMap;
    }
}

