/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitiesResponse } from './entitiesResponse';
import { FactsResponse } from './factsResponse';
import { FactsResponseDocuments } from './factsResponseDocuments';
import { KeywordsResponse } from './keywordsResponse';
import { LanguagesResponse } from './languagesResponse';
import { SentimentsResponse } from './sentimentsResponse';
import { TokensResponse } from './tokensResponse';

export class GetTaskResultSuccess {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return GetTaskResultSuccess.attributeTypeMap;
    }
}

