/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PerOperationLimitConstantResponse {
    /**
    * The maximum number of text units that can be processed in all time
    */
    'nTULimit'?: number;
    /**
    * Counter of text units that have been already processed for operation Text parsing
    */
    'nTUTokens'?: number;
    /**
    * Counter of text units that have been already processed for operation Keywords extraction
    */
    'nTUKeywords'?: number;
    /**
    * Counter of text units that have been already processed for operation Entities extraction
    */
    'nTUEntities'?: number;
    /**
    * Counter of text units that have been already processed for operation Language detection
    */
    'nTULanguages'?: number;
    /**
    * Counter of text units that have been already processed for operation Sentiments analysis
    */
    'nTUSentiments'?: number;
    /**
    * Counter of text units that have been already processed for operation Facts extraction
    */
    'nTUFacts'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nTULimit",
            "baseName": "NTULimit",
            "type": "number"
        },
        {
            "name": "nTUTokens",
            "baseName": "NTUTokens",
            "type": "number"
        },
        {
            "name": "nTUKeywords",
            "baseName": "NTUKeywords",
            "type": "number"
        },
        {
            "name": "nTUEntities",
            "baseName": "NTUEntities",
            "type": "number"
        },
        {
            "name": "nTULanguages",
            "baseName": "NTULanguages",
            "type": "number"
        },
        {
            "name": "nTUSentiments",
            "baseName": "NTUSentiments",
            "type": "number"
        },
        {
            "name": "nTUFacts",
            "baseName": "NTUFacts",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PerOperationLimitConstantResponse.attributeTypeMap;
    }
}

