/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PerOperationLimitPeriodic2Response {
    /**
    * A period when limitations apply
    */
    'nTUPeriod2'?: PerOperationLimitPeriodic2Response.NTUPeriod2Enum;
    /**
    * A maximum number of requests in the specified period
    */
    'nTUInPeriod2Limit'?: number;
    /**
    * A number of requests that have already been processed for operation Text parsing
    */
    'nTUInPeriod2Tokens'?: number;
    /**
    * A number of requests that have already been processed for operation Keywords extraction
    */
    'nTUInPeriod2Keywords'?: number;
    /**
    * A number of requests that have already been processed for operation Entities extraction
    */
    'nTUInPeriod2Entities'?: number;
    /**
    * A number of requests that have already been processed for operation Language detection
    */
    'nTUInPeriod2Languages'?: number;
    /**
    * A number of requests that have already been processed for operation Sentiments analysis
    */
    'nTUInPeriod2Sentiments'?: number;
    /**
    * A number of requests that have already been processed for operation Facts extraction
    */
    'nTUInPeriod2Facts'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nTUPeriod2",
            "baseName": "NTUPeriod2",
            "type": "PerOperationLimitPeriodic2Response.NTUPeriod2Enum"
        },
        {
            "name": "nTUInPeriod2Limit",
            "baseName": "NTUInPeriod2Limit",
            "type": "number"
        },
        {
            "name": "nTUInPeriod2Tokens",
            "baseName": "NTUInPeriod2Tokens",
            "type": "number"
        },
        {
            "name": "nTUInPeriod2Keywords",
            "baseName": "NTUInPeriod2Keywords",
            "type": "number"
        },
        {
            "name": "nTUInPeriod2Entities",
            "baseName": "NTUInPeriod2Entities",
            "type": "number"
        },
        {
            "name": "nTUInPeriod2Languages",
            "baseName": "NTUInPeriod2Languages",
            "type": "number"
        },
        {
            "name": "nTUInPeriod2Sentiments",
            "baseName": "NTUInPeriod2Sentiments",
            "type": "number"
        },
        {
            "name": "nTUInPeriod2Facts",
            "baseName": "NTUInPeriod2Facts",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PerOperationLimitPeriodic2Response.attributeTypeMap;
    }
}

export namespace PerOperationLimitPeriodic2Response {
    export enum NTUPeriod2Enum {
        Second = <any> 'Second',
        Minute = <any> 'Minute',
        Hour = <any> 'Hour',
        Day = <any> 'Day',
        Month = <any> 'Month'
    }
}
