/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerOperationLimitConstantResponse } from './perOperationLimitConstantResponse';
import { PerOperationLimitPeriodic1Response } from './perOperationLimitPeriodic1Response';
import { PerOperationLimitPeriodic2Response } from './perOperationLimitPeriodic2Response';

export class PerOperationLimitResponse {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return PerOperationLimitResponse.attributeTypeMap;
    }
}

export namespace PerOperationLimitResponse {
}
