/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SentimentsResponseAttributes } from './sentimentsResponseAttributes';
import { SentimentsResponsePositions } from './sentimentsResponsePositions';

export class SentimentsResponseSentiments {
    /**
    * Sentiment type
    */
    'type'?: SentimentsResponseSentiments.TypeEnum;
    'attributes'?: SentimentsResponseAttributes;
    /**
    * Sentiment positions in text
    */
    'positions'?: Array<SentimentsResponsePositions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SentimentsResponseSentiments.TypeEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SentimentsResponseAttributes"
        },
        {
            "name": "positions",
            "baseName": "positions",
            "type": "Array<SentimentsResponsePositions>"
        }    ];

    static getAttributeTypeMap() {
        return SentimentsResponseSentiments.attributeTypeMap;
    }
}

export namespace SentimentsResponseSentiments {
    export enum TypeEnum {
        Positive = <any> 'Positive',
        Negative = <any> 'Negative'
    }
}
