/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ServerInfo {
    /**
    * Server version
    */
    'version'?: string;
    /**
    * List of supported languages
    */
    'languages'?: Array<string>;
    /**
    * List of supported operations
    */
    'operations'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<string>"
        },
        {
            "name": "operations",
            "baseName": "operations",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ServerInfo.attributeTypeMap;
    }
}

