/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskInfoTasks } from './taskInfoTasks';

export class TaskInfo {
    /**
    * List of user tasks
    */
    'tasks'?: Array<TaskInfoTasks>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskInfoTasks>"
        }    ];

    static getAttributeTypeMap() {
        return TaskInfo.attributeTypeMap;
    }
}

