/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TokensResponsePosition } from './tokensResponsePosition';

export class TokensResponseTokens {
    /**
    * Word as in text
    */
    'word'?: string;
    /**
    * A dictionary form of a word, e.g. given verb forms \"run\", \"ran\" and \"runs\", \"run\" is the lemma
    */
    'lemma'?: string;
    /**
    * Assigns a word to a morphological category according to each syntactic functions.
    */
    'partOfSpeech'?: TokensResponseTokens.PartOfSpeechEnum;
    /**
    * One of the grammatical categories of a word, e.g. person for verbs or number for nouns. Each part of speech has its own set of modifiers.  The detailed list of parameters can be found in Help to TM API Server. 
    */
    'modifier'?: any;
    /**
    * Indicates a way of writing a token with the previous one. It returns \"1\", if tokens are written as a single token. It returns \"0\", if tokens are written separately. 
    */
    'isExtension'?: TokensResponseTokens.IsExtensionEnum;
    'position'?: TokensResponsePosition;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "word",
            "baseName": "word",
            "type": "string"
        },
        {
            "name": "lemma",
            "baseName": "lemma",
            "type": "string"
        },
        {
            "name": "partOfSpeech",
            "baseName": "partOfSpeech",
            "type": "TokensResponseTokens.PartOfSpeechEnum"
        },
        {
            "name": "modifier",
            "baseName": "modifier",
            "type": "any"
        },
        {
            "name": "isExtension",
            "baseName": "isExtension",
            "type": "TokensResponseTokens.IsExtensionEnum"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "TokensResponsePosition"
        }    ];

    static getAttributeTypeMap() {
        return TokensResponseTokens.attributeTypeMap;
    }
}

export namespace TokensResponseTokens {
    export enum PartOfSpeechEnum {
        Noun = <any> 'Noun',
        Verb = <any> 'Verb',
        Adverb = <any> 'Adverb',
        Adjective = <any> 'Adjective',
        Particle = <any> 'Particle',
        Pronoun = <any> 'Pronoun',
        Numeral = <any> 'Numeral',
        Special = <any> 'Special',
        Punctuation = <any> 'Punctuation'
    }
    export enum IsExtensionEnum {
        NUMBER_0 = <any> 0,
        NUMBER_1 = <any> 1
    }
}
