/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Token position in text
*/
export class TokensResponsePosition {
    /**
    * Symbol position of token begining in text (starts with 0)
    */
    'begin'?: number;
    /**
    * Token length in symbols
    */
    'length'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "begin",
            "baseName": "begin",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TokensResponsePosition.attributeTypeMap;
    }
}

