/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TotalLimitPeriodic1Response {
    /**
    * A period when limitations apply
    */
    'nTUPeriod1'?: TotalLimitPeriodic1Response.NTUPeriod1Enum;
    /**
    * A maximum number of requests in the specified period
    */
    'nTUInPeriod1Limit'?: number;
    /**
    * A number of requests that have already been processed
    */
    'nTUInPeriod1'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nTUPeriod1",
            "baseName": "NTUPeriod1",
            "type": "TotalLimitPeriodic1Response.NTUPeriod1Enum"
        },
        {
            "name": "nTUInPeriod1Limit",
            "baseName": "NTUInPeriod1Limit",
            "type": "number"
        },
        {
            "name": "nTUInPeriod1",
            "baseName": "NTUInPeriod1",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TotalLimitPeriodic1Response.attributeTypeMap;
    }
}

export namespace TotalLimitPeriodic1Response {
    export enum NTUPeriod1Enum {
        Second = <any> 'Second',
        Minute = <any> 'Minute',
        Hour = <any> 'Hour',
        Day = <any> 'Day',
        Month = <any> 'Month'
    }
}
