/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TotalLimitPeriodic2Response {
    /**
    * A period when limitations apply
    */
    'nTUPeriod2'?: TotalLimitPeriodic2Response.NTUPeriod2Enum;
    /**
    * A maximum number of requests in the specified period
    */
    'nTUInPeriod2Limit'?: number;
    /**
    * A number of requests that have already been processed
    */
    'nTUInPeriod2'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nTUPeriod2",
            "baseName": "NTUPeriod2",
            "type": "TotalLimitPeriodic2Response.NTUPeriod2Enum"
        },
        {
            "name": "nTUInPeriod2Limit",
            "baseName": "NTUInPeriod2Limit",
            "type": "number"
        },
        {
            "name": "nTUInPeriod2",
            "baseName": "NTUInPeriod2",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TotalLimitPeriodic2Response.attributeTypeMap;
    }
}

export namespace TotalLimitPeriodic2Response {
    export enum NTUPeriod2Enum {
        Second = <any> 'Second',
        Minute = <any> 'Minute',
        Hour = <any> 'Hour',
        Day = <any> 'Day',
        Month = <any> 'Month'
    }
}
