/**
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TotalLimitConstantResponse } from './totalLimitConstantResponse';
import { TotalLimitPeriodic1Response } from './totalLimitPeriodic1Response';
import { TotalLimitPeriodic2Response } from './totalLimitPeriodic2Response';

export class TotalLimitResponse {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return TotalLimitResponse.attributeTypeMap;
    }
}

export namespace TotalLimitResponse {
}
